// Pine Script v.5
// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © DevSergo [.com] aka kiti-kiti

//@version = 5

indicator(title="Daily Range | Volatility in persental %%", shorttitle="Daily Range Volatility [© DevSergo [.com] aka kiti-kiti]")

amplitude = ((high - low)/((high+low)/2))*100
average30 = ta.sma(amplitude, 30)
average3 = ta.sma(amplitude, 3)
average3_5 = ta.sma(average3, 3)

plot(amplitude, style=plot.style_columns, color=color.silver)
plot(average30, color=color.blue)
plot(average3, color=color.red)
plot(average3_5, color=color.green)
